name: ddd_logger
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  logger: ^1.1.0

dev_dependencies:
  build_runner: ^2.2.0
  freezed: ^2.0.3+1
  freezed_annotation: ^2.0.3
  json_annotation: ^4.8.0
  json_serializable: ^6.0.1
  lints: ^2.0.0
  test: ^1.16.0
